import { formatDate, formatINR, formatINRWhole } from './format.js'

const LOW_STOCK = 5

export const masterConfigs = {
  products: {
    title: 'Product Master',
    singular: 'product',
    endpoint: '/api/products',
    listKey: 'products',
    itemKey: 'product',
    searchFields: ['name', 'brand', 'category'],
    columns: [
      {
        label: 'Product',
        value: (p) => p.name,
        detail: (p) => [p.brand, p.size].filter(Boolean).join(' · '),
      },
      { label: 'Category', value: (p) => p.category },
      { label: 'Price', align: 'right', mono: true, value: (p) => formatINR(p.price) },
      {
        label: 'Stock',
        align: 'right',
        mono: true,
        value: (p) => String(p.stock),
        tone: (p) => (p.stock <= LOW_STOCK ? 'warn' : undefined),
      },
    ],
    fields: [
      { name: 'name', label: 'Product name', required: true, maxLength: 100, wide: true },
      { name: 'brand', label: 'Brand', maxLength: 100, suggest: true },
      { name: 'category', label: 'Category', required: true, maxLength: 50, suggest: true },
      { name: 'size', label: 'Size', maxLength: 30, placeholder: 'e.g. 250 ml' },
      { name: 'price', label: 'Price (₹)', type: 'number', required: true, min: 0, step: '0.01' },
      { name: 'stock', label: 'Stock on hand', type: 'number', required: true, min: 0, step: '1' },
      { name: 'description', label: 'Description', type: 'textarea', maxLength: 2000, wide: true },
    ],
  },

  services: {
    title: 'Service Master',
    singular: 'service',
    endpoint: '/api/services',
    listKey: 'services',
    itemKey: 'service',
    searchFields: ['name', 'category', 'description'],
    columns: [
      { label: 'Service', value: (s) => s.name, detail: (s) => s.description },
      { label: 'Category', value: (s) => s.category },
      { label: 'Duration', align: 'right', mono: true, value: (s) => `${s.durationMinutes} min` },
      { label: 'Price', align: 'right', mono: true, value: (s) => formatINR(s.price) },
    ],
    fields: [
      { name: 'name', label: 'Service name', required: true, maxLength: 100, wide: true },
      { name: 'category', label: 'Category', required: true, maxLength: 50, suggest: true },
      {
        name: 'durationMinutes',
        label: 'Duration (minutes)',
        type: 'number',
        required: true,
        min: 5,
        max: 720,
        step: '5',
      },
      { name: 'price', label: 'Price (₹)', type: 'number', required: true, min: 0, step: '0.01' },
      { name: 'description', label: 'Description', type: 'textarea', maxLength: 2000, wide: true },
    ],
  },

  employees: {
    title: 'Employee Master',
    singular: 'employee',
    endpoint: '/api/employees',
    listKey: 'employees',
    itemKey: 'employee',
    inactiveHint: 'Inactive employees stay on record but are marked as no longer working here.',
    searchFields: ['name', 'employeeCode', 'designation', 'phone', 'email'],
    columns: [
      { label: 'Employee', value: (e) => e.name, detail: (e) => e.employeeCode },
      { label: 'Designation', value: (e) => e.designation },
      { label: 'Contact', mono: true, value: (e) => e.phone, detail: (e) => e.email },
      {
        label: 'Joined',
        mono: true,
        value: (e) => (e.joiningDate ? formatDate(`${e.joiningDate}T00:00`) : '—'),
      },
      {
        label: 'Commission',
        align: 'right',
        mono: true,
        value: (e) => `${e.commissionPercent}%`,
      },
    ],
    fields: [
      { name: 'name', label: 'Full name', required: true, maxLength: 100, wide: true },
      {
        name: 'employeeCode',
        label: 'Employee code',
        required: true,
        maxLength: 20,
        pattern: '[A-Za-z0-9_\\-]{2,20}',
        placeholder: 'e.g. EMP005',
        uppercase: true,
      },
      {
        name: 'designation',
        label: 'Designation',
        required: true,
        maxLength: 50,
        suggest: true,
        placeholder: 'e.g. Hair Stylist',
      },
      {
        name: 'phone',
        label: 'Mobile number',
        type: 'tel',
        required: true,
        maxLength: 20,
        pattern: '\\+?[0-9 \\-]{10,19}',
        placeholder: 'e.g. 98765 43210',
      },
      { name: 'email', label: 'Email', type: 'email', maxLength: 255 },
      { name: 'joiningDate', label: 'Joining date', type: 'date' },
      {
        name: 'commissionPercent',
        label: 'Commission (%)',
        type: 'number',
        min: 0,
        max: 100,
        step: '0.01',
        hint: 'Share of service value; leave blank for 0',
      },
    ],
  },

  coupons: {
    title: 'Coupon Master',
    singular: 'coupon',
    endpoint: '/api/coupons',
    listKey: 'coupons',
    itemKey: 'coupon',
    searchFields: ['code', 'description'],
    columns: [
      { label: 'Code', mono: true, value: (c) => c.code, detail: (c) => c.description },
      {
        label: 'Discount',
        align: 'right',
        mono: true,
        value: (c) =>
          c.discountType === 'percent' ? `${c.discountValue}%` : formatINRWhole(c.discountValue),
        detail: (c) => (c.maxDiscount ? `up to ${formatINRWhole(c.maxDiscount)}` : ''),
      },
      {
        label: 'Min. Folio',
        align: 'right',
        mono: true,
        value: (c) => (c.minSubtotal > 0 ? formatINRWhole(c.minSubtotal) : '—'),
      },
    ],
    fields: [
      {
        name: 'code',
        label: 'Coupon code',
        required: true,
        maxLength: 30,
        pattern: '[A-Za-z0-9_\\-]{3,30}',
        hint: '3–30 letters, numbers, - or _',
        uppercase: true,
      },
      {
        name: 'discountType',
        label: 'Discount type',
        type: 'select',
        required: true,
        defaultValue: 'percent',
        options: [
          { value: 'percent', label: 'Percentage (%)' },
          { value: 'flat', label: 'Flat amount (₹)' },
        ],
      },
      {
        name: 'discountValue',
        label: 'Discount value',
        type: 'number',
        required: true,
        min: 0.01,
        step: '0.01',
        max: (values) => (values.discountType === 'percent' ? 100 : undefined),
      },
      {
        name: 'maxDiscount',
        label: 'Maximum discount (₹)',
        type: 'number',
        min: 0.01,
        step: '0.01',
        hint: 'Leave blank for no cap',
        showIf: (values) => values.discountType === 'percent',
      },
      {
        name: 'minSubtotal',
        label: 'Minimum folio value (₹)',
        type: 'number',
        min: 0,
        step: '0.01',
        hint: 'Leave blank for no minimum',
      },
      { name: 'description', label: 'Description', type: 'textarea', maxLength: 255, wide: true },
    ],
  },
}
